AYHF-MVC/Areas/Admin/Controllers/OrderController.cs
using AYHF.DataAccess.Repository;
using AYHF.DataAccess.Repository.IRepository;
using AYHF.Models;
using AYHF.Models.ViewModels;
using AYHF.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AYHF_MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderVM OrderVM { get; set; }

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int orderId)
        {
            OrderVM = new()
            {
                OrderHeader = _unitOfWork.OrderHeaderRepo.GetFirstOrDefault(u => u.Id == orderId, includeProperties: "ApplicationUser"),
                OrderDetails = _unitOfWork.OrderDetailRepo.GetAll(u => u.OrderHeaderId == orderId, includeProperties: "Product")
            };
            return View(OrderVM);
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult UpdateOrderDetail()
        {
            var orderHeader = _unitOfWork.OrderHeaderRepo.GetFirstOrDefault(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeader.Name = OrderVM.OrderHeader.Name;
            orderHeader.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
            orderHeader.StreetAddress = OrderVM.OrderHeader.StreetAddress;
            orderHeader.City = OrderVM.OrderHeader.City;
            orderHeader.State = OrderVM.OrderHeader.State;
            orderHeader.PostalCode = OrderVM.OrderHeader.PostalCode;

            if (!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier))
            {
                orderHeader.Carrier = OrderVM.OrderHeader.Carrier;
            }
            if(!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
            {
                orderHeader.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            }

            _unitOfWork.OrderHeaderRepo.Update(orderHeader);
            _unitOfWork.Save();
            TempData["success"] = "Order Detail updated successfully";

            return RedirectToAction(nameof(Details), new {orderId = orderHeader.Id});
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Shipper)]
        public IActionResult StartPackaging()
        {
            
            _unitOfWork.OrderHeaderRepo.UpdateStatus(OrderVM.OrderHeader.Id, SD.StatusPackaging);
            _unitOfWork.Save();
            TempData["success"] = "Order start packaging...";

            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Shipper)]
        public IActionResult DonePackaging()
        {

            _unitOfWork.OrderHeaderRepo.UpdateStatus(OrderVM.OrderHeader.Id, SD.StatusPacked);
            _unitOfWork.Save();
            TempData["success"] = "Order packed";

            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Shipper)]
        public IActionResult ShipOrder()
        {
            var orderHeader = _unitOfWork.OrderHeaderRepo.GetFirstOrDefault(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeader.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            orderHeader.Carrier = OrderVM.OrderHeader.Carrier;
            orderHeader.OrderStatus = SD.StatusShipping;
            orderHeader.ShippingDate = DateTime.Now;
            _unitOfWork.OrderHeaderRepo.Update(orderHeader);
            _unitOfWork.Save();
            TempData["success"] = "Order start shipping...";

            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Shipper)]
        public IActionResult ShipConfirm()
        {

            _unitOfWork.OrderHeaderRepo.UpdateStatus(OrderVM.OrderHeader.Id, SD.StatusShipped);
            _unitOfWork.Save();
            TempData["success"] = "Order shipped";

            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Customer)]
        public IActionResult CancelOrder()
        {

            _unitOfWork.OrderHeaderRepo.UpdateStatus(OrderVM.OrderHeader.Id, SD.StatusCancelled);
            _unitOfWork.Save();
            TempData["success"] = "Order Cancelled";

            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }



        #region API CALLS
        [HttpGet]
        public IActionResult GetAll(string status)
        {
            IEnumerable<OrderHeader> obj;

            if (User.IsInRole(SD.Role_Admin))
            {
                obj = _unitOfWork.OrderHeaderRepo.GetAll(includeProperties: "ApplicationUser").ToList();
            
            } else if (User.IsInRole(SD.Role_Shipper))
            {
                obj = _unitOfWork.OrderHeaderRepo.GetAll(
                    u => (u.OrderStatus == SD.StatusShipping 
                    || u.OrderStatus == SD.StatusPackaging
                    || u.OrderStatus == SD.StatusPacked
                    || u.OrderStatus == SD.StatusApproved) 
                    && u.PaymentStatus == SD.PaymentStatusApproved, includeProperties: "ApplicationUser").ToList();

            } else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                obj = _unitOfWork.OrderHeaderRepo.GetAll(u=>u.ApplicationUserId == claim, includeProperties:"ApplicationUser");
            }

            switch (status)
            {
                case "pending":
                    obj = obj.Where(u => u.PaymentStatus == SD.PaymentStatusPending);
                    break;
                case "completed":
                    obj = obj.Where(u => u.OrderStatus == SD.StatusShipped);
                    break;
                case "approved":
                    obj = obj.Where(u => u.OrderStatus == SD.StatusApproved);

                    break;
                case "shipping":
                    obj = obj.Where(u => u.OrderStatus == SD.StatusShipping);

                    break;
                case "packaging":
                    obj = obj.Where(u => u.OrderStatus == SD.StatusPackaging);

                    break;
                case "packed":
                    obj = obj.Where(u => u.OrderStatus == SD.StatusPacked);

                    break;
                case "all":
                    
                    break;
            }

            return Json(new { data = obj });
        }

        
        #endregion
    }

}

AYHF-MVC/Areas/Customer/Controllers/CartController.cs
using AYHF.DataAccess.Repository;
using AYHF.DataAccess.Repository.IRepository;
using AYHF.Models;
using AYHF.Models.ViewModels;
using AYHF.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AYHF_MVC.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public ShoppingCartVM CartVM {  get; set; }
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            
        }
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            CartVM = new()
            {
                ShoppingCartList = _unitOfWork.CartRepo.GetAll(u => u.ApplicationUserId == userId,
                includeProperties: "Product"),
                OrderHeader = new()
                
            };

            

            foreach(var cart in CartVM.ShoppingCartList)
            {
                CartVM.OrderHeader.OrderTotal += cart.Product.Price * cart.Count;
            }
            
            return View(CartVM);
        }

        public IActionResult GenerateInvoice()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            CartVM = new()
            {
                ShoppingCartList = _unitOfWork.CartRepo.GetAll(u => u.ApplicationUserId == userId,
                includeProperties: "Product"),
                OrderHeader = new()

            };

            CartVM.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUserRepo.GetFirstOrDefault(u => u.Id == userId);
            CartVM.OrderHeader.PhoneNumber = CartVM.OrderHeader.ApplicationUser.PhoneNumber;
			CartVM.OrderHeader.StreetAddress = CartVM.OrderHeader.ApplicationUser.StreetAddress;
			CartVM.OrderHeader.City = CartVM.OrderHeader.ApplicationUser.City;
			CartVM.OrderHeader.State = CartVM.OrderHeader.ApplicationUser.State;
			CartVM.OrderHeader.PostalCode = CartVM.OrderHeader.ApplicationUser.PostalCode;
			CartVM.OrderHeader.Name = CartVM.OrderHeader.ApplicationUser.Name;



			foreach (var cart in CartVM.ShoppingCartList)
            {
                CartVM.OrderHeader.OrderTotal += cart.Product.Price * cart.Count;
            }
            return View(CartVM);
        }

        [HttpPost]
        [ActionName("GenerateInvoice")]
		public IActionResult GenerateInvoicePOST()
		{
            
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            CartVM.ShoppingCartList = _unitOfWork.CartRepo.GetAll(u => u.ApplicationUserId == userId,
                includeProperties: "Product");


            CartVM.OrderHeader.OrderDate = DateTime.Now;
            CartVM.OrderHeader.ApplicationUserId = userId;
			CartVM.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUserRepo.GetFirstOrDefault(u => u.Id == userId);

            if(CartVM.ShoppingCartList.Count() == 0)
            {
                TempData["error"] = "No item in cart!";
                return RedirectToAction(nameof(Index));
            }

			foreach (var cart in CartVM.ShoppingCartList)
			{
				CartVM.OrderHeader.OrderTotal += cart.Product.Price * cart.Count;
			}

            CartVM.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            CartVM.OrderHeader.OrderStatus = SD.StatusPending;
			
            _unitOfWork.OrderHeaderRepo.Add(CartVM.OrderHeader);
            _unitOfWork.Save();
            foreach (var cart in CartVM.ShoppingCartList)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    ProductId = cart.ProductId,
                    OrderHeaderId = CartVM.OrderHeader.Id,
                    Count = cart.Count,
                };
                _unitOfWork.OrderDetailRepo.Add(orderDetail);
				_unitOfWork.Save();
			}





			
			return RedirectToAction("ConfirmPayment", "Payment", new { area = "Customer",id = CartVM.OrderHeader.Id });
		}


        
       
		public IActionResult Plus(int cartId)
        {
            var cart = _unitOfWork.CartRepo.GetFirstOrDefault(u => u.Id == cartId);
            cart.Count += 1;
            _unitOfWork.CartRepo.Update(cart);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Minus(int cartId)
        {
            var cart = _unitOfWork.CartRepo.GetFirstOrDefault(u => u.Id == cartId);
            if(cart.Count <= 1)
            {
                _unitOfWork.CartRepo.Remove(cart);
            } 
            else
            {
                cart.Count -= 1;
                _unitOfWork.CartRepo.Update(cart);
            }
            
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Remove(int cartId)
        {
            var cart = _unitOfWork.CartRepo.GetFirstOrDefault(u => u.Id == cartId);
            
            _unitOfWork.CartRepo.Remove(cart);
            

            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

AYHF-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AYHF_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AYHF_MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <link href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AYHF_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                   Stock Manager
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    

                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-cart"></i> &nbsp; 
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted " data-bs-theme="dark">
        <div class="container">
            &copy; 2024 - AYHF_MVC
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AYHF-MVC/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
    
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}